import type { Metadata } from "next";
import { Albert_Sans, Gloock } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const albertSans = Albert_Sans({subsets:['latin'],variable:'--font-albert'});
const gloock = Gloock({subsets:['latin'],variable:'--font-gloock', weight:'400'});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", albertSans.variable, gloock.variable, "font-mono", "font-gloock")}
    >
      <body className="min-h-full flex flex-col font-mono items-center">{children}</body>
    </html>
  );
}
